project_id = "yfrdymnqjjqgboefiolr"

[functions.attendance-process]
verify_jwt = true

[functions.compose-quick-message]
verify_jwt = true

[functions.convert-to-employee]
verify_jwt = true

[functions.hr-home-snapshot]
verify_jwt = true

[functions.leave-autofill]  
verify_jwt = true

[functions.leave-compute-days]
verify_jwt = true

[functions.leave-set-status]
verify_jwt = true

[functions.note-toggle-pin]
verify_jwt = true

[functions.offer-accept]
verify_jwt = false

[functions.offer-decline]
verify_jwt = false

[functions.offer-generate-html]
verify_jwt = true

[functions.offer-issue]
verify_jwt = true

[functions.payroll-compute]
verify_jwt = true

[functions.payroll-mark-paid]
verify_jwt = true

[functions.payroll-render-payslip]
verify_jwt = true

[functions.reminder-mark-done]
verify_jwt = true

[functions.seed-initial-users]
verify_jwt = false