// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfrdymnqjjqgboefiolr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmcmR5bW5xampxZ2JvZWZpb2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTkzMDUsImV4cCI6MjA3MjAzNTMwNX0.MUzmZq0t37zhAp7Dxrzn35RaM22Rt0Smcmc5bo-tdWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: false, // Disable automatic refresh
  }
});